# Generated by Django 5.1.1 on 2024-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcard',
            name='commander',
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
